### ISSUE TITLE
FlatList - Getting sum of items 

### ISSUE THREAD

**Issue by marcpassarelli** [HandlebarLabs/code-and-coffee#11]
## Question Description

I have a Flatlist showing a list of products and their prices (just like an online shopping cart). I also render for each item a plus and a minus icon wrapped inside a TouchableOpacity that I use to set the quantity I want of each product.

So what I want to do and I don’t know how is after I decided the quantity of each product, I want to get the sum of prices.

Do you know how I could do that?

## How can I get started?

My FlatList:

```javascript
<FlatList
        ItemSeparatorComponent={this.renderSeparator}
        data= {listaAdicionais}
        extraData={this.state}
        renderItem={({item}) =>
        <AdicionaisListItem
          nameAdditional = {item.name}
          price = {item.price}>
        </AdicionaisListItem>}
        keyExtractor={item => item.nome}
      />
```

The component AdicionaisListItem used in the renderItem:

```javascript
export default class AdicionaisListItem extends Component {
  constructor(props) {
    super(props);
    this.state = {
      qty:0
    }
  }

  minusQty(){
    let qty = this.state.qty
    if(qty!=0){
      this.setState({
        qty: qty - 1
      });
    }
  }

  plusQty(){
    let qty = this.state.qty + 1
    this.setState({
      qty: qty
    });
  }

  render() {
    return (
      <View style={{flex: 1, flexDirection: 'row', marginTop: 5, justifyContent: 'space-between'}}>
        <View style={{flex:1}}>
          <Text style={styles.textAdicionais}>
            {this.props.nameAdditional}
          </Text>
        </View>
        <View style={{flex:1}}>
          <Text style={styles.textAdicionais}>
            R$ {this.props.price*this.state.qty}
          </Text>
        </View>

        <View style={{flex:1, flexDirection: 'row', justifyContent: 'flex-end', marginRight: 10}}>
          <TouchableOpacity
            style={{justifyContent: 'center', alignSelf: 'center', marginBottom: 10}}
            onPress={()=>{this.minusQty()}}>
            <Image
              source={require('../../img/minus.png')}
              style={styles.icon}/>
          </TouchableOpacity>
          <Text
            style={styles.textAdicionais}>
            {this.state.qty}
          </Text>
          <TouchableOpacity
            style={{justifyContent: 'center', alignSelf: 'center', marginBottom: 10}}
            onPress={()=>{this.plusQty()}}>
            <Image
              source={require('../../img/plus.png')}
              style={styles.icon}/>
          </TouchableOpacity>
        </View>
      </View>
    );
  }
}
```
![image](https://user-images.githubusercontent.com/25596926/35516315-963743d6-04f2-11e8-928f-43c7d1461a46.png)

Let me know if there is any further information I could provide you

**Comment by spencercarli** [comment]
Great question! I put together a video showing how I would approach this task - I hope it helps you!

[<img width="1665" alt="screen shot 2018-01-31 at 3 26 10 pm" src="https://user-images.githubusercontent.com/1105429/35648552-b5c71e92-069b-11e8-8a65-10f8bfdb0f10.png">](https://www.youtube.com/watch?v=6rngDlYtnBM&feature=youtu.be)


And here's the code for the demo

```javascript
import React from 'react';
import { View, Text, FlatList, Button, SafeAreaView, processColor } from 'react-native';

const products = [
  { _id: 1, name: 'Item 1', price: 50, quantity: 0 },
  { _id: 2, name: 'Item 2', price: 29, quantity: 0 },
  { _id: 3, name: 'Item 3', price: 200, quantity: 0 },
];

class ListItem extends React.Component {
  render() {
    const { item } = this.props;

    return (
      <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}>
        <View style={{ flexDirection: 'row', flex: 1, alignItems: 'center' }}>
          <Text>{item.name} - </Text>
          <Text>{item.price}</Text>
        </View>
        <View style={{ flexDirection: 'row', flex: 1, alignItems: 'center' }}>
          <Button title="Subtract" onPress={this.props.onSubtract} />
          <Text>{item.quantity}</Text>
          <Button title="Add" onPress={this.props.onAdd} />
        </View>
      </View>
    )
  }
}

class App extends React.Component {
  state = {
    products,
  };

  onSubtract = (item, index) => {
    const products = [...this.state.products];
    products[index].quantity -= 1;
    this.setState({ products });
  }

  onAdd = (item, index) => {
    const products = [...this.state.products];
    products[index].quantity += 1;
    this.setState({ products });
  }

  render() {
    const { products } = this.state;
    let totalQuantity = 0;
    let totalPrice = 0;
    products.forEach((item) => {
      totalQuantity += item.quantity;
      totalPrice += item.quantity * item.price;
    })

    return (
      <SafeAreaView style={{ flex: 1 }}>
        <FlatList
          data={this.state.products}
          renderItem={({ item, index }) => (
            <ListItem
              item={item}
              onSubtract={() => this.onSubtract(item, index)}
              onAdd={() => this.onAdd(item, index)}
            />
          )}
          keyExtractor={item => item._id}
        />
        <Text>Total Quantity: {totalQuantity}</Text>
        <Text>Total Price: {totalPrice}</Text>
      </SafeAreaView>
    );
  }
}

export default App;
```

**Comment by rajkishoreandia** [comment]
i am getting scroll To function error while the flatlist is horizental.but in case of horizental false the drop down is working fine.please help thanks
--------------------------------------------------------------
import React, { Component } from "react";
import { SearchBar, Card } from "react-native-elements";
import { Dropdown } from "react-native-material-dropdown";
import {Select, Option} from "react-native-chooser";
import {
  Platform,
  StyleSheet,Button,
  AsyncStorage,
  Text,Picker,Alert,
  ImageBackground,
  ScrollView,
  BackHandler,
  View,
  TouchableOpacity,
  Animated,
  Image,
  FlatList
} from "react-native";
import { Actions } from "react-native-router-flux";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp
} from "react-native-responsive-screen";

import {
  Content,
  List,
  Header,
  ListItem,
  InputGroup,
  Input,
  Label,
  // Picker,
  Item,
  Icon,
  Container,
  Left,
  Right,
  Badge
} from "native-base";
const Sliding_Drawer_Width = 410;
// const deviceHeight = Dimensions.get("window").height;
// const deviceWidth = Dimensions.get("window").width;
var i = 1;
var addQty = [];
const products = [];

export default class Support extends Component {
  goBack() {
    Actions.login();
  }
  componentDidMount() {
    // alert(this.props.islooggedIn)
    if(this.props.islooggedIn){
      this.backHandler = BackHandler.addEventListener("hardwareBackPress", () => {
        // this.goBack(); // works best when the goBack is async
        return true;
      });
    }
    else{
      this.backHandler = BackHandler.addEventListener("hardwareBackPress", () => {
        this.goBack(); // works best when the goBack is async
      });
    }
    this.productList();
  }
  productList() {
    fetch("http://donation.ucdemos.biz/v1/login/view-products", {
      method: "GET"
    })
      .then(response => response.json())
      .then(responseJson => {
        console.log(responseJson);
        console.log("responseJson.length = " + responseJson.length);
        for (let i = 0; i < responseJson.product_list.length; i++) {
          addQty[i] = 0;
        }
        this.setState({
          products: responseJson.product_list

          // console.log(data);
        });

        console.log(this.state.products);
      })
      .catch(error => {
        console.error(error);
      });
     for (let i = 0; i < products.length; i++) {
            addQty[i] = 0;
          }
          this.setState({
            products: products
  
            // console.log(data);
          });
  }
  componentWillUnmount() {
    this.backHandler.remove();
  }

  logout() {
    Actions.login();
  }
  Dashboard() {
    Actions.Dashboard();
  }

  displayStorageData = async () => {
    try {
      this.StoredUser = await AsyncStorage.getItem("user_name");
      console.log(this.StoredUser);
    } catch (error) {
      alert(error);
    }
  };
  Report() {
    Actions.Report();
    // ShowSlidingDrawer();
  }
  Profile() {
    Actions.Profile();
  }
  // Settings() {
  //   Actions.Settings()
  // }
  Support() {
    Actions.Support();
  }
  About() {
    Actions.About();
  }

  constructor(props) {
    super(props);
    this.displayStorageData();
    this.state = {
      products:[],
      i: 3,
      StoredUser: "",
      inputQty: 0
    };


  }
 
  onSubtract = (item, index) => {
    addQty[index] -= 1;
    if(addQty[index]<0){
      addQty[index] = 0;
    }
    console.log("in minus click" + addQty);
    const products = [...this.state.products];
    products[index].quantity -= 1;
    this.setState({ products });

    console.log("state = " + JSON.stringify(this.state.products));
  };
  GetSelectedPickerItem(itemValue, itemIndex){
      console.log('in picker selected method'+itemValue,itemIndex);
      this.setState(
        {PickerValueHolder: itemValue}
      )
    Alert.alert(this.state.PickerValueHolder);
  }

  Checkout() {
    // Actions.Checkout({properties:this.state})
    console.log("state = " + this.state);
    Actions.Checkout({ text: true });
  }
  onAdd = (item, index) => {
    addQty[index] += 1;
    console.log("in plus click" + addQty);
    const products = [...this.state.products];
    products[index].quantity += 1;
    this.setState({ products });
    console.log("state = " + JSON.stringify(this.state.products));
  };

  ShowSlidingDrawer = () => {
    this.displayStorageData();

    if (this.Sliding_Drawer_Toggle === true) {
      Animated.timing(this.Animation, {
        toValue: 1,
        duration: 500
      }).start(() => {
        this.Sliding_Drawer_Toggle = false;
      });
    } else {
      Animated.timing(this.Animation, {
        toValue: 0,
        duration: 500
      }).start(() => {
        this.Sliding_Drawer_Toggle = true;
      });
    }
  };

  render() {
    const { inputQty } = this.state;
  
    const { products } = this.state;
    let totalQuantity = 0;
    let totalPrice = 0;
    let individualItemTotalQuantity = 0;
    let dr = [];
    let priceData = [];
    for (let i = 0; i < products.length; i++) {
      let options1 = [];
      let options2 = [];

      let pro = products[i].products;
      for (let j = 0; j < pro.length; j++) {
        options1[j] = { value: pro[j].quantity };
        options2[j] =pro[j].price;
      }
      dr[i] = options1;
      priceData[i] = options2;
      console.log(dr[i]);
    }
    products.forEach(item => {
      if (item.quantity >= 0) {
        totalQuantity += item.quantity;
        individualItemTotalQuantity += item.quantity * item.price;
        totalPrice += item.quantity * item.price;
      }
    });

    return (
      <View style={styles.container}>
       
        <View style={{ flex: 1, width: "100%" }}>
        <ScrollView>
          <FlatList
          scrollToOffset={{animated:false}}
          horizontal={false}
            data={this.state.products}
            renderItem={({ item, index }) => (
              <View style={styles.ListCssStyle}>
                <Image
                  source={require("../images/item1.jpg")}
                  style={styles.productImageStyle}
                />
                <View style={styles.plusImage}>
                  <Text style={styles.productTextStyle}>{item.name} </Text>
                  <Text style={styles.productTextStyle1}>${priceData[index][0]}</Text>
                </View>
                <View style={{ flexDirection: "row", width: 100 }}>
                  <TouchableOpacity onPress={() => this.onAdd(item, index)}>
                    <Image
                      source={require("../images/Plus.png")}
                      style={styles.plusCss}
                    />
                  </TouchableOpacity>
                  <Text style={styles.quantityTextCss}> {addQty[index]}</Text>
                  <TouchableOpacity
                    onPress={() => this.onSubtract(item, index)}
                  >
                    <Image
                      source={require("../images/Minus.png")}
                      style={styles.plusCss1}
                    />
                  </TouchableOpacity>
                </View>
                <View style={styles.dropDownCss}>
                <Dropdown
                dropdownOffset={{top:5,left:10,position:'absolute'}}

                   containerStyle={{
                     width: 100,
                     backgroundColor: "transparent"
                   }}
                   inputContainerStyle={styles.dropDownTextCss}
                   data={dr[index]}
                   value={dr[index][0].value}
                 />
        
       <Text style={styles.totalCss}>
      Total : {item.quantity * item.price}
      </Text> 
                </View>
              </View>
            )}
          />
             </ScrollView>
        </View>

      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    // justifyContent: 'center',
    alignItems: "center",
    backgroundColor: "#F1F2F2"
  },
  header: {
    // flex: 1,
    width: wp("100%"),
    height: 50,
    backgroundColor: "#00E676",
    flexDirection: "row"
  },
  header1: {},
  container1: {
    flex: 1,
    marginTop: hp("15%")
  },
  Root_Sliding_Drawer_Container: {
    position: "absolute",
    flexDirection: "row",
    left: 0,
    top: 0,
    //top: (Platform.OS == 'ios') ? 20 : 0,
    width: Sliding_Drawer_Width,
    height: "100%"
    //   justifyContent:'center',alignItems:'center',
  },

  Main_Sliding_Drawer_Container: {
    flex: 1,
    backgroundColor: "#F1F2F2",
    paddingHorizontal: 10,
    justifyContent: "center",
    alignItems: "center"
  },

  TextStyle: {
    fontSize: 20,
    padding: 10,
    textAlign: "center",
    color: "black"
  },
  imgBackground: {
    width: "100%",
    height: "100%",
    flex: 1
  },
  ImageStyle: {
    padding: 0,
    marginTop: 100,
    borderRadius: 100,
    borderWidth: 2,
    borderColor: '#00E676',
    height: 100,
    width: 100,
    // resizeMode: "stretch",
    justifyContent: "center",
    alignItems: "center"
  },
  ImageStyle1: {
    padding: 0,
    height: 30,
    width: 30,
    resizeMode: "stretch"
  },
  text: {
    // fontWeight: Platform.OS === "ios" ? "500" : "400",
    fontSize: 20,
    marginLeft: 20,
    color: "black"
  },
  labelStyle: {
    fontSize: 20,
    fontFamily: "AVP-Alleyn-Medium",
    marginLeft: 20,
    color: "black"
  },
  iconStyle: {
    padding: 0,
    height: 25,
    width: 25,
    // resizeMode : 'stretch',
    //   marginRight: -30,
    marginLeft: 50
  },
  listStyle: {
    height: hp("10%"),
    // borderColor:white'
    borderBottomColor: "#00E676",
    borderBottomWidth: 1
  },
  listStyle2: {
    height: hp("10%"),
    // borderColor:white'
    borderTopColor: "#00E676",
    borderTopWidth: 1,
    borderBottomColor: "#00E676",
    borderBottomWidth: 1
  },
  listStyle1: {
    marginLeft: -250,
    paddingLeft: 60,
    height: hp("100%"),

    marginRight: -180
  },
  drawerImage: {
    position: "absolute",
    width: 210,
    height: 75,
    resizeMode: "cover"
  },
  badgeText: {
    fontSize: Platform.OS === "ios" ? 13 : 11,
    fontWeight: "400",
    textAlign: "center"
  },
  inputgroup: {
    backgroundColor: "#ABF9C5",
    height: 30,
    marginTop: "2%",
    marginLeft: "2%",
    marginRight: "2%",
    borderRadius: 50,
    borderWidth: 1,
    borderColor: "#00E676"
  },
  button: {
    width: 100,
    height: 40,
    // marginLeft: 30,
    backgroundColor: "#05C962",
    borderRadius: 5,
    marginTop: 5,
    marginBottom: 5,
    borderWidth: 2,
    justifyContent: "center",
    alignItems: "center",
    borderColor: "white"
  },
  buttonText: {
    fontSize: 20,
    fontFamily: "AVP-Alleyn-Semibold",
    color: "white",
    textAlign: "center"
    // paddingTop:5
  },
  cityImgStyle: {
    width: 30,
    height: 30,
    // marginLeft:40,
    marginTop: 10,
    position: "absolute",
    flexDirection: "row",
    left: wp("87%"),
    top: 0,
    justifyContent: "flex-end",
    alignItems: "flex-end"
  },
  productImageStyle: {
    width: 70,
    height: 70,
    margin: 10
    // borderColor: '#00E676',
    // borderWidth:1,
    // borderRadius:100
  },
  ListCssStyle: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "white",
    marginTop: 5,
    height: 90
  },
  productTextStyle: {
    marginTop: 10,
    fontFamily: "AVP-Alleyn-Regular",
    fontSize: 15,
    color: "black"
  },
  productTextStyle1: {
    marginTop: 2,
    fontFamily: "AVP-Alleyn-Regular",
    fontSize: 15,
    color: "black"
  },
  plusCss: {
    width: 20,
    height: 20,
    marginTop: 10
  },
  plusCss1: {
    width: 20,
    height: 20,
    marginTop: 10,
    marginLeft: 5
  },
  dropDownCss: {
    position:'relative',
    flex: 1,
    flexDirection: "row",
    marginTop: 55,
    // marginLeft:wp('-70%')
    width: 100,
    marginLeft: -300,
    backgroundColor:'transparent'
  },
  dropDownTextCss: {
    borderBottomColor: "transparent",
    paddingLeft: 15,
    // paddingBottom:10 ,
    paddingTop: -25,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#00E676",
    height: 23,
    justifyContent: "center"
  },
  plusImage: {
    width: wp("50%")
  },
  totalCss: {
    // marginLeft:wp('14 %'),
    marginLeft: 60,
    fontFamily: " AVP-Alleyn-Regular",
    fontFamily: "",
    fontSize: 15,
    color: "black",
    marginTop: 0,
    marginBottom: 10,
    alignItems: "center",
    justifyContent: "flex-end"
  },
  quantityTextCss: {
    marginTop: 10,
    justifyContent: "center",
    alignItems: "center",
    fontFamily: " AVP-Alleyn-Regular",
    color: "black"
  },
  quantityContainerCss: {
    width: wp("10%"),
    alignItems: "center"
  },
  headerText: {
    fontSize: 25,
    fontFamily: "AVP-Alleyn-Semibold",
    justifyContent: "center",
    alignItems: "center",
    color: "white",
    marginLeft: 100,
    marginTop: 10,
    marginBottom: 5
  },
  sidemenuText:{
    fontSize: 20,
    color: "black",
    // fontWeight: "400",
    marginTop: 10,
    fontFamily: "AVP-Alleyn-Medium"
  }
});

**Comment by parthsoni021194** [comment]
how to fetch the products from mysql and use in this code using fetch(your API)

**Comment by mustafakameldev** [comment]
> Great question! I put together a video showing how I would approach this task - I hope it helps you!
> 
> [<img alt="screen shot 2018-01-31 at 3 26 10 pm" width="1665" src="https://user-images.githubusercontent.com/1105429/35648552-b5c71e92-069b-11e8-8a65-10f8bfdb0f10.png">](https://www.youtube.com/watch?v=6rngDlYtnBM&feature=youtu.be)
> 
> And here's the code for the demo
> 
> ```js
> import React from 'react';
> import { View, Text, FlatList, Button, SafeAreaView, processColor } from 'react-native';
> 
> const products = [
>   { _id: 1, name: 'Item 1', price: 50, quantity: 0 },
>   { _id: 2, name: 'Item 2', price: 29, quantity: 0 },
>   { _id: 3, name: 'Item 3', price: 200, quantity: 0 },
> ];
> 
> class ListItem extends React.Component {
>   render() {
>     const { item } = this.props;
> 
>     return (
>       <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}>
>         <View style={{ flexDirection: 'row', flex: 1, alignItems: 'center' }}>
>           <Text>{item.name} - </Text>
>           <Text>{item.price}</Text>
>         </View>
>         <View style={{ flexDirection: 'row', flex: 1, alignItems: 'center' }}>
>           <Button title="Subtract" onPress={this.props.onSubtract} />
>           <Text>{item.quantity}</Text>
>           <Button title="Add" onPress={this.props.onAdd} />
>         </View>
>       </View>
>     )
>   }
> }
> 
> class App extends React.Component {
>   state = {
>     products,
>   };
> 
>   onSubtract = (item, index) => {
>     const products = [...this.state.products];
>     products[index].quantity -= 1;
>     this.setState({ products });
>   }
> 
>   onAdd = (item, index) => {
>     const products = [...this.state.products];
>     products[index].quantity += 1;
>     this.setState({ products });
>   }
> 
>   render() {
>     const { products } = this.state;
>     let totalQuantity = 0;
>     let totalPrice = 0;
>     products.forEach((item) => {
>       totalQuantity += item.quantity;
>       totalPrice += item.quantity * item.price;
>     })
> 
>     return (
>       <SafeAreaView style={{ flex: 1 }}>
>         <FlatList
>           data={this.state.products}
>           renderItem={({ item, index }) => (
>             <ListItem
>               item={item}
>               onSubtract={() => this.onSubtract(item, index)}
>               onAdd={() => this.onAdd(item, index)}
>             />
>           )}
>           keyExtractor={item => item._id}
>         />
>         <Text>Total Quantity: {totalQuantity}</Text>
>         <Text>Total Price: {totalPrice}</Text>
>       </SafeAreaView>
>     );
>   }
> }
> 
> export default App;
> ```
i tried this code but the text doesn't change
