### ISSUE TITLE
Splash screen showing every time app comes from background to active and mount current component again.

### ISSUE THREAD

**Issue by Shhzdmrz** [HandlebarLabs/code-and-coffee#17]
Hi Spencer,

## Issue
I followed your article to add splash screen in android app but its giving weird behavior every time app state change from background to active, it shows splash screen every time and mount the component again. 

I noticed this when I was calling a redux action for the api request in componentDidMount method calling twice or you can say that how many time my app comes from background to active. Noticeable issue occur when app receive notification using react-native-push-notification. Once I click on the notification component mounting the screen again that already mounted by showing splash again.

I don't know this behaviour is because of the react native single activity android app or may be I am adding the splash activity above the main activity.

So, I have created a test project to resolve this issue. 

I also tried splash without adding another activity using rn-splash-screen package but that will give me white screen before splash or you can say on the cold start.

As I am not a native android developer but I want to make a splash like twitter, uber which show splash on the cold start. You can find my splash screen test repo [**here**](https://github.com/Shhzdmrz/SplashTest)

Another thing I want to show splash on full screen.

## Solution
At last I am able to resolve this issue changing the **launch mode for Main Activity** 
See **AndroidManifest.xml** `android:launchMode="singleTask"`. As react navigation is handled by Main Activity so I added launchMode as singleTask to avoid launching same activity again.

For the full screen splash I used `SplashScreen.show(this, true);` in the main activity where first parameter is referring to activity instance and second parameter is referring to fullscreen flag to show splash on fullscreen and this is not documented in the react-native-splash-screen repo. 

Maybe you should update the article or test with my repo may be I was doing something wrong. By the way except for these two changes I followed your article on medium.

**Comment by spencercarli** [comment]
So the only change necessary to fix this was adding [this line](https://github.com/Shhzdmrz/SplashTest/blob/master/android/app/src/main/AndroidManifest.xml#L34)?

**Comment by Shhzdmrz** [comment]
yes that was the only line that fixed the issue.

**Comment by Shhzdmrz** [comment]
by the way Spencer make a repo or some web page to list all your articles in a single place as you are explaining well all important part of react native. 

P.S. I am following your articles since the day one of my react native learning and I have many question in my mind to discuss with you. Thank you so much for all your efforts.

**Comment by rhysgoehring** [comment]
I was having the same issue using react-native-push-notification-ce. When pressing on a local notification my app was relaunching to the initial screen in my route navigation (now showing the splash like @Shhzdmrz). 

Just adding the `android:launchMode="singleTask"` line fixed everything and the app now goes from the background directly back into whatever screen you were on before. 

Thanks @Shhzdmrz for your solution and @spencercarli for all the great learning resources you provide.
