### ISSUE TITLE
'This' binding and creating class methods with arrow functions?

### ISSUE THREAD

**Issue by ehutchllew** [HandlebarLabs/code-and-coffee#6]
## Question Description

I've been working with React Native for a few months now, and though I would say I'm mostly comfortable there are still some enigmas. One of these enigmas is the appropriate location to bind(this) and arrow functions' role in that.

1) What is the difference between the below class methods?

2) Are these two different ways to declare a method with the same result?

3) Lastly, when is it a good idea to bind(this) in the constructor vs the render method (or any other location in the component).

Hope this makes sense, and thank you!

## How can I get started?

1)
```
_renderItem(){
//difference between this
}

_renderItem = () => {
//and this
}
```

2)
```
constructor(){
    super();
    this._renderItem = this._renderItem.bind(this);
}

_renderItem(){
//code code code
}
```
```
_renderItem = () => {
//code code code
```

**Please note:** In order to keep consistency and ensure maximum clarity in your question I may edit it.

**Comment by spencercarli** [comment]
Thanks for the question! I tried answering it this [this video](https://youtu.be/E4U-2jq8g44) but I think writing it out can be more clear.

Basically, they're all valid ways to do it and they'll give you the same result.

When using the arrow function method, `_renderItem = () => {}`, you're relying on the transpiler to make sure that's actually valid. Fortunately, React Native does that for you out of the box. If you were working in a different environment that didn't transpile that then you would run into an error along the lines of `Uncaught SyntaxError: Unexpected token =`.

For your final question - if you're going to be using `bind(this)` always do so in the constructor that way it's only called once. If it's in the `render`, or potentially other places, it can run multiple times.

Hope this added some clarity!

[This is a good resource](https://ponyfoo.com/articles/binding-methods-to-class-instance-objects) to check out.
