### ISSUE TITLE
Facebook Login Issue

### ISSUE THREAD

**Issue by AbubakarSambo** [HandlebarLabs/code-and-coffee#7]
## Question Description

I'm trying to implement facebook login on my react-native app in conjunction with a node/express server. when i try to use `react-native-fbsdk`, it seems login happens on the client exclusively but i need the flow to include hitting my server and registering the user.

**Comment by spencercarli** [comment]
Happy to look into this but can you put together an example of how I can get up and running with this?

**Comment by spencercarli** [comment]
Going to close this since there hasn't been a followup.
