### ISSUE TITLE
Promises, Asynchronous Logic, and State

### ISSUE THREAD

**Issue by parappathekappa** [HandlebarLabs/code-and-coffee#8]
## Question Description

We have a component that has loads of asynchronous logic built into it.  We have each functional bit chunked out into individual methods.  However, it still seems cluttered, inefficient and difficult to debug.

We're wondering what the best way it to handle lots of asynchronous logic in a react-native app, and how best to tie it into state.  We came up with 3 of our own ways to skin this cat.  We'd like to know what the best way is, and what some potential pitfalls could be with any of the methods.

And with all of these methods, we'd like to know how best to use promises to handle the asynchronous stuff.  We could use some real hand-holding with promises :) . Pro tips, best practices...

## How can I get started?

Code Sample Here: https://gist.github.com/parappathekappa/000cb565c7bfc57fb3821a07ec7405c6

There are two file versions, V1, and V2.  I didn't include a V3 option.  masterFunction() kicks everything off in all versions, and it's called in componentWillMount().

Version 1:
All function logic is stored as methods inside the component class.  Each method updates the state.

Version 2:
All function logic is stored as external utils files.  They don't update state, but rather take predetermined inputs and outputs.  A main function inside the component calls all these utils files, and updates the state as it receives responses.

Version 3 (not in the gist):
All function logic is stored as external utils files as in Version 2, but the utils functions update the state on their own.  The main function inside the component calls the utils functions, but does not need to update the state.  It relies on state to get the information it needs, so it doesn't use any outputs from the utils functions.

**Comment by spencercarli** [comment]
Definitely a lot going on here 😄 

Initial thoughts - I think a lot of this logic would be better served being pulled out of the component and into something like [`redux-saga`](https://redux-saga.js.org/) or [`redux-thunk`](https://github.com/gaearon/redux-thunk).

Now, if that's not something you wish to do I would typically go with something along the lines of V2. Why? It's easier to test and just reason about in general because you're separating concerns in a more clear way.

I think the `getAddresses` function could also be simplified more as well. Currently you're

1. Repeatedly making that request until the desired accuracy is reached
2. Doing reverse geocode
3. Modifying redux state (this is why I pointed you to redux-saga or redux-thunk)
4. Fetching multiple addresses

Here's how I would break it down - this is purely pseudo code and copy & paste. It probably has an error in it...

```javascript
class AddressList extends Component {
  ...

  reverseGeocode = () => {
    Location.reverseGeocodeAsync({
      latitude: location.coords.latitude,
      longitude: location.coords.longitude,
    })
    .then((response) => {
      // Update the state with Expo Address
      console.log('Expo Address Returned');
      this.props.dispatch(setExpoAddresses(response));
    })
    .catch((error) => {
      console.error(error);
    });
  }

  getMultipleAddresses = () => {
    getMultipleAddressesFromApi(location)
    .then((masterlist) => {
      // Update the state with list from API
      console.log('API Addresses Returned');
      this.props.dispatch(setAddresses(masterlist));
    })
    .then(() => {
      // Select the correct addy from the list
      const selectedAddy = pickAddy(
        this.props.options.house,
        this.props.expoAddresses,
        this.props.addresses,
      );
      this.props.dispatch(selectAddress(selectedAddy.myNewAddy));
      this.theone = selectedAddy.theone;
      this.props.dispatch(setAddressStatus('All loaded!'));
    })
    .catch((error) => {
      console.error(error);
    });
  }

  getAddresses = () => {
    // Get the users location
    const myLocation = getLocationAsync().then((location) => {
      if (location.coords.accuracy <= 1000) {
        console.log('Accuracy Reached!');
        
        this.props.dispatch(setLocation(location));
        this.props.dispatch(setAddressStatus('Loading Address List...'));
        
        this.reverseGeocode();
        this.getMultipleAddresses();
      } else {
        console.log(`Accuracy: ${location.coords.accuracy}`);
        // Repeat every second until the accuracy threshold is reached
        setTimeout(() => {
          this.getAddresses();
        }, 1000);
      }
    });
  };

  ...
}
```

I find this code much more readable and you can see what promises depend on others to finish for success to happen and, upon a quick glance at code, it's easier to figure out what's going on.

Let me know if that helps and if you've got any followup question(s)!

**Comment by parappathekappa** [comment]
That's great beta, thanks so much for the feedback.

I also have some general questions about Promises.  Whenever I look them up online I see that you can instantiate a promise by:
```javascript
var promise = new Promise(function(resolve, reject) {} );
```

However, in a lot of the react code we're using we're creating external functions that use 'async' in the function call:
```javascript
export async function getAddressesFromApi(latitude, longitude) {};
```

Are these two different ways to instantiate a promise, and if so, what are pros and cons of each?

Thanks,
Bryan

**Comment by spencercarli** [comment]
As far as I know there's only one way to create a promise and that's via 

```javascript
var promise = new Promise(function(resolve, reject) {} );
```

However, there are two ways to consume them. The "normal" way and the async/await way. 

The normal:
```javascript
const doTheThing = () => {
  promise
    .then((result) => console.log('do something with the result', result))
    .catch((error) => console.log('uh oh, an error occurred', error));
};
```

And the async/await way:
```javascript
const doTheThing = async () => {
  try {
    const result = await promise();
    console.log('do something with the result', result)
  } catch (error) {
    console.log('uh oh, an error occurred', error))
  }
};
```

The benefit of the latter approach is that when you're reading it (and as it's executing) it's more of synchronous function.

**Comment by parappathekappa** [comment]
Perfect.  Thank you!

More followup questions (if that's ok).  What is the best practice around nesting promises, or chained promises?  The .then() seems like an easy system for chaining promises together, but I'm not really sure what the .then() returns.  Does it return another promise, or just a response object?  I've seen code with lots of .then()'s chained together which seems like it could be handy, if you know how to wield it.

This is part of a bigger question: why does Javascript need promises, and why can't it reliably execute code synchronously from top to bottom like other languages (like Python)?  It seems like the intent of promises is to do multiple things asynchronously to save time.  However, I find myself using it exclusively to just make sure that the d$*! code executes in the order that I want it to.

This is probably a more intense computer science question that's out of my pay grade, but I like to ask questions!

**Comment by spencercarli** [comment]
I'm not sure about best practices, but I can show you some code from a project I'm working on!

Here I'm using a combo of the "normal" promises chain and async/await because it resulted in the easiest to read code. In short, I've seeded a database and certain tables depend on other data existing - I've commented the code with more details.

```javascript
exports.seed = knex =>
  // Deletes ALL existing entries
  clearDB(knex)
    // Creates a user. This func returns a promise that, when resolved, returns my newly created 
    // user
    .then(() => createUser())
    // Select all the users and all their data from the db. This returns a promise that, when 
    // resolved, returns an array of users
    .then(() => knex("users").select("*"))
    .then(async users => {
      // Create a profile for each user in the database. The createProfile func returns a promise
      const chain = users.map(user => createProfile(user));
      // Wait for all the profiles to be created before moving on
      await Promise.all(chain);
      // Return the array of users we created earlier
      return users;
    })
    .then(async users => {
      // Create a diagnosis for each user in the database. The createDiagnosis func returns a 
      // promise
      const chain = users.map(user => createDiagnosis(user));
      // Wait for all the diagnoses to be created before moving on
      await Promise.all(chain);
      // Return the array of users we created earlier
      return users;
    })
    .then(async users => {
      // Create a daily log for each user in the database. The createDailyLogs func itself creates 
      // an array of promises so I flatten the array of arrays 
      // ([[p1, p2], [p3, p4]] => [p1, p2, p3, p4]) so I can wait for each one to resolve later
      const chain = _.flattenDeep(users.map(user => createDailyLogs(user)));
      // Wait for all the daily logs to be created before moving on
      await Promise.all(chain);
      // Return the array of users we created earlier
      return users;
    });
```

I don't really know why things are the way they are, but I can show you how I use things now 😄

**Comment by spencercarli** [comment]
Gonna go ahead and close this 😄
