### ISSUE TITLE
React Navigation - transitionConfig & Custom Navigators

### ISSUE THREAD

**Issue by ehutchllew** [HandlebarLabs/code-and-coffee#9]
## Question Description

Hey Spencer, thanks again for all your help. I wanted to know if you had any plans to do a video, or series, on creating custom transition animations with React Navigation and even creating our own navigators?

**Comment by spencercarli** [comment]
Hey @ehutchllew - great question! I don't have plans on doing anything with creating custom navigators but I did put together an example of how to customize navigation transitions.

You can find [that code here](https://github.com/HandlebarLabs/react-navigation-cookbook/blob/custom-transition/App/custom-transition/index.js#L41).

It's part of a larger egghead.io course dedicated to React Navigation that's currently under review. I'll post a link to it once the course is published 😄
